export enum CardChoiceCode {
  ZONE_A_VALIDITY_90_MINUTES = "A90",
  ZONE_B_VALIDITY_90_MINUTES = "B90",
  ZONE_A_AND_B_VALIDITY_90_MINUTES = "C90",
  ZONE_A_VALIDITY_1_DAY = "A1",
  ZONE_B_VALIDITY_1_DAY = "B1",
  ZONE_A_AND_B_VALIDITY_1_DAY = "C1",
  ZONE_A_VALIDITY_7_DAYS = "A7",
  ZONE_B_VALIDITY_7_DAYS = "B7",
  ZONE_A_AND_B_VALIDITY_7_DAYS = "C7",
  ZONE_A_VALIDITY_30_DAYS = "A30",
  ZONE_B_VALIDITY_30_DAYS = "B30",
  ZONE_A_AND_B_VALIDITY_30_DAYS = "C30",
}
